### ISSUE TITLE
SSDT-RX580.aml for other mobo

### ISSUE THREAD

**Issue by rickdgit** [29satnam/Skylake-RX580-Hackintosh#1]
Hi

I also have a Sapphire RX580 Pulse 8GB for my hackintosh but running on a Z370 with i7-8700k.
I wonder what does this SSDT used for and how can I use it on my mobo?

Im trying to solve the sleep wake problem...

Thanks!

**Comment by 29satnam** [comment]
I really don't know what's that for, but poor config.plist configuration cause sleep wake issue AFAIK.

**Comment by rickdgit** [comment]
Thanks! 
Do you still use this aml for Catalina ?

**Comment by 29satnam** [comment]
> Thanks!
> Do you still use this aml for Catalina ?

I switched to OpenCore and I'm not using it.
